* Project proposal
  Name: Nathan Bhat, Marcus Granström

* Name of the app
  QuakeSee

* Short description
  The application will display earthquake activity around the world in real time (updated every 5 minutes). The earthquake activity will be rendered on a map from google maps. 
  The user will be able to:
- specify criteria for which earthquakes that should be shown (magnitude etc...). 
- view earthquakes that occurred in the area for the last couple of days by draggning a slider. 
- save favourite localtions and preferences of which earthquakes they are interested in, magnitude, location etc... 
- users can report own info (casualties, needs for supply etc...) which will be tagged with coordinates and ploted on the map. Other users should be able to wrtie comments to theses reports.
  
* Framework(s) that will be used
  ReactJS, Firebase, Node.js.

* API that will be used
  https://earthquake.usgs.gov/ & https://developers.google.com/maps/documentation/javascript/

* What data will your app work with (which ones come from API and which one is your app specific)
  Both the map and the earthquake data will be provided via the api's. The userdata will be provided from the backend and will contain settings and saved earthquakes etc... 
  
* Quick mock-up/prototype (paper drawing is fine) of the screens your app will have

  https://app.moqups.com/marcus.granstroem@gmail.com/Rl581gpcpK/view
